
CXX		= $(LARCV_CXX)
LD              = $(LARCV_CXX) #g++
LDFLAGS         += -Wl,-rpath,$(LARCV_BASEDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared
CXXFLAGS        += -g -O3 -std=c++0x -fopenmp -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = $(LARCV_CXX) #g++
SOFLAGS         = -g -fPIC -lgomp -shared

ifeq ($(LARCV_OPENCV),1)
CXXFLAGS += -DUSE_OPENCV
endif
